# Generated by Django 5.2.5 on 2025-08-26 13:44

import yandex_cloud.custom_media_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(storage=yandex_cloud.custom_media_storage.MediaStorage(), upload_to='photos/')),
            ],
        ),
    ]
